### PR TITLE
fix: missing title in notification for rocketchat v4

### PR DESCRIPTION
**Pull request by fabiottini**
Problem with the rocketchat v4 notification, must have the title field.

### CODE REVIEW

**Comment by oliviermaridat** [comment]
Dear @fabiottini 

Thanks a lot for the PR. I was not aware of this change in Rocket.chat v4. Do you have a screenshot of the rendering please?

I have 2 questions:
- Why did you replace `(?:#|n°)` by `#` in the regex? In some translations, the ticket number is displayed with "n°189" instead of "#189"
- Why did you remove `comment.delete`? It is pretty useful.

Thanks!

**Comment by fabiottini** [comment]
Hi @oliviermaridat ,

it's no possible to do the chat rendering because it crashes without the fix.

I had upgraded the chat and when I entered in the chats with the autogenerated messages by the plugin, rocket.chat web interface or desktop app crash immediately. Instead I have no problem with mobile phone app.

I have created a new channel to send autogenerated messages by plugin, I have done a reverse engineering on the messages processed by the rocket.chat web source code to understood  witch is the problem and I understood  that I had problems only when in the messages is not present the title information.
I have opened the source code of the plugin and I added the two rows that you found in the merge:
- [Row 89](https://github.com/oliviermaridat/plugin-rocketchat/pull/1/commits/749852cf4f4d3266f94edb62a6008e17fd18065e#diff-742e5e9e88d36229d0b324a7dd0b11f9123a4d3f643db07c50b16aec64824155R89)
- [Row 92](https://github.com/oliviermaridat/plugin-rocketchat/pull/1/commits/749852cf4f4d3266f94edb62a6008e17fd18065e#diff-742e5e9e88d36229d0b324a7dd0b11f9123a4d3f643db07c50b16aec64824155R92)

To reply to your 2 question:

1. I think it's a test and i forgot to restore the correct code... sorry! I fix and push the correct version.
2. The same as point 1 

Thanks!

**Comment by oliviermaridat** [comment]
Ok thanks @fabiottini 
Are you sure the change is pushed?

**Comment by fabiottini** [comment]
Hi @oliviermaridat, 

now yes! Sorry I was involved in a meeting and I forgot to push it!

Thanks

**Comment by oliviermaridat** [comment]
Thanks a lot @fabiottini

**Comment by oliviermaridat** [comment]
I merged your PR. Now I need to create a new release and push it to fguillot. I will do that later.

**Comment by oliviermaridat** [comment]
Done. Waiting merge on KB website side.

**Pull request merged**
